# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e31ee200e4a4634c42cbad61ff30e0f41059fefe591bb2e6d071e262c3ef3aa50145f22d86493e30d79495c0514e0e9468368f349c0bac861e9ab0784ba1b1b

test:
  secret_key_base: 020810a60c0cf7f5116d7f4d7dcbe5f2a56268a15cd96bec06855792772971b382574fd9dd5a20da2a8146fd4fb71952f98605eaa1923ffdea4ab308cd0fe6a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
